name: FlaskTest documentation publication on GitHub

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
      - name: Install dependencies
        run: make VENV= venv.update
      - name: Check documentation syntax
        run: make VENV= check.docs
      - name: Generate documentation
        run: make VENV= docs
      - name: Upload to GitHub Pages
        uses: actions/upload-pages-artifact@v3
  # NOTE separate jobs because this one requires authn data
  deploy:
    environment:
      name: github-pages
    needs: build
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
